name: Divar Job Bot

on:
  schedule:
    - cron: "30 7 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python scraper.py

      - name: Check seen ads
        run: |
          echo "===== seen_ads.json ====="
          cat seen_ads.json
          echo "========================="

      - name: Save seen ads
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git status
          git add -f seen_ads.json

          git diff --cached -- seen_ads.json

          git commit -m "Update seen ads" || true

          git status

          git push origin HEAD:main
